### ISSUE TITLE
Android: PlatformException (PlatformException(AuthError:Failed, Plugin not attached to any activity., null))

### ISSUE THREAD

**Issue by acoutts** [authpass/biometric_storage#1]
Can't seem to write to storage with Android, I'm getting the error:
```
Exception has occurred.
PlatformException (PlatformException(AuthError:Failed, Plugin not attached to any activity., null))
```

Here's how I'm calling it (followed how it was done in the example):
```dart
    var b = await BiometricStorage().getStorage('li.my.app',
        options: StorageFileInitOptions(authenticationRequired: true));
    await b.write('some new data');
```

Flutter information:
```
Flutter 1.12.13+hotfix.7 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9f5ff2306b (2 weeks ago) • 2020-01-26 22:38:26 -0800
Engine • revision a67792536c
Tools • Dart 2.7.0
```

**Comment by acoutts** [comment]
After some digging, the activity being returned when we extend `ActivityAware` is not a fragment activity.

Do we need a fragment activity for this plugin to work?

**Comment by hpoul** [comment]
Yes you do, see https://github.com/authpass/biometric_storage#android .. make sure to use the one from the embedding package.

**Comment by hpoul** [comment]
you can also check out the example: https://github.com/authpass/biometric_storage/blob/master/example/android/app/src/main/kotlin/design/codeux/biometric_storage_example/MainActivity.kt

**Comment by acoutts** [comment]
Ah sorry, I meant to post earlier that I did figure it out - by doing exactly that. Thanks!
