### ISSUE TITLE
5.0.1-dev.1 returns CanAuthenticate.sucess if device has no credentials set

### ISSUE THREAD

**Issue by SylvainLosey** [authpass/biometric_storage#104]
Hello,

I might be misunderstanding something, but it seems that the latest dev version has an oversight where canAuthenticate would return successfully whenever the device has no credentials enrolled. This does not seem like the expected behavior, am I missing something ?

```        
        val credentialsResponse = biometricManager.canAuthenticate(DEVICE_CREDENTIAL);
        logger.debug { "canAuthenticate for DEVICE_CREDENTIAL: $credentialsResponse" }
        if (credentialsResponse == BiometricManager.BIOMETRIC_ERROR_NONE_ENROLLED) {
            return CanAuthenticateResponse.Success
        }
```

Thanks a lot for the great package,
Sylvain

**Comment by OlliePorter** [comment]
Seconded! We're using `5.0.0+1` and calling the canAuthenticate function as so, but we're getting back a success when it should be a failure.

```
 Future<bool> isDeviceEligible() =>
      storage.canAuthenticate().then((value) => value == CanAuthenticateResponse.success);
```

The emulator we're using is an iPhone 15 Pro with Face ID capabilities, but these have not been set up. The device is not enrolled, so we're expecting canAuthenticate to return `errorNoBiometricEnrolled`.

**Comment by 10ndavis** [comment]
@hpoul is this plugin still being maintained? This issue seems critical, as it defeats the purpose of the plugin entirely if biometrics do not prompt.

**Comment by SylvainLosey** [comment]
Agreed. For information I fixed the issue for our internal use, I will try to find the time to clean it up and raise a PR but it would be good to know if someone is still available to get it reviewed and merged.
