### ISSUE TITLE
5.0.0+4 Flutter plugin cannot access BiometricStoragePlugin

### ISSUE THREAD

**Issue by andiilhamsyahidris** [authpass/biometric_storage#106]
i have some trouble when i want to used Biometric Storage. Flutter plugin cannot access BiometricStoragePlugin. I don't know how to solve it

<img width="749" alt="Screenshot 2023-12-07 114904" src="https://github.com/authpass/biometric_storage/assets/54732809/50d3a8a2-3e4d-473d-bda1-6bc7b5b1d8b0">

**Comment by RootSoft** [comment]
@andiilhamsyahidris Looks like you need to update your JAVA SDK to 17

**Comment by andiilhamsyahidris** [comment]
> @andiilhamsyahidris Looks like you need to update your JAVA SDK to 17

I am already using Java SDK version 17

**Comment by vlad-buhaescu-qoob** [comment]
my temporary fix is to remove 

kotlin {
    jvmToolchain(17)
}

from the libary's Gradle file at /Users/"yourUser"/.pub-cache/hosted/pub.dev/biometric_storage-5.0.0+4/android/build.gradle
