### ISSUE TITLE
No signature of method: build_71y17k4eyt1asltzpoo9zhmdo.kotlin() is applicable for argument types: (build_71y17k4eyt1asltzpoo9zhmdo$_run_closure2) values: [build_71y17k4eyt1asltzpoo9zhmdo$_run_closure2@5fdb5b92]   Possible solutions: notify(), toString(), toString(), toString(), toString(), split(groovy.lang.Closure)

### ISSUE THREAD

**Issue by scmwinlinaung** [authpass/biometric_storage#110]
I found an above issue when I run my app in android.

**Comment by tahitiangabriel** [comment]
I also had this problem because I was using an old Kotlin version (1.6.10).
When I move to version 1.8.22 it works like a charm.

**Comment by hpoul** [comment]
sounds to me as well that it's related to an old kotlin version or kotlin gradle plugin or similar.. try updating all dependencies if it's still not working let me know.
