### ISSUE TITLE
biometric_storage does not build with Java 21

### ISSUE THREAD

**Issue by connyduck** [authpass/biometric_storage#117]
We are upgrading our project to Java 21 and the only package that is causing issues is biometric_storage.
Yes, a possible workaround is to have both JDK 17 and 21 installed via gradle toolchains, but it would be very nice to need only one, e.g. for CI/CD.
Please check if you can make biometric_storage work with Java 17 and up instead of explicitly requiring 17.

**Comment by hpoul** [comment]
since the code is all kotlin, this should be a pretty minor change.. feel free to provide a PR, I should be able to review it pretty quickly..

**Comment by hpoul** [comment]
thanks, i actually haven't tested it (yet), maybe you could give `5.1.0-rc.4` a try. 😅

**Comment by connyduck** [comment]
@hpoul 5.1.0-rc.4 works fine in a Java 21 only project now! When will 5.1.0 be released?

**Comment by GuvanchBayryyyev** [comment]
it still gives me an error 
`Execution failed for task ':biometric_storage:compileReleaseJavaWithJavac'. `
`> error: invalid source release: 17`
