### ISSUE TITLE
Question: How to use "authenticationValidityDurationSeconds"?

### ISSUE THREAD

**Issue by croquies** [authpass/biometric_storage#15]
Hi,

Thank you for making this package.

`StorageFileInitOptions(
            authenticationValidityDurationSeconds: 30,
),`

As far as I understand, when I set authenticationValidityDurationSeconds to 30, the storage file should not require authentication for 30 seconds for any read or write actions.

But my working sample with Samsung Galaxy Note 10 asks authentication per every actions (read and write).
(no matter how long I set the validity duration).

Thank for your help!

Wonmo

**Comment by radvansky-tomas** [comment]
Same for Mac OSX

**Comment by hpoul** [comment]
just take a look at the implementation. on macOS:
https://github.com/authpass/biometric_storage/blob/a9fad0aad3aaa220c03cb609999c7432e88c6e5c/macos/Classes/BiometricStorageImpl.swift#L151

on android:

https://github.com/authpass/biometric_storage/blob/ee9d42722487b27bdbd360dd80e46d337b2b909d/android/src/main/kotlin/design/codeux/biometric_storage/BiometricStorageFile.kt#L43-L44

feel free to look at the corresponding native platform documentation on what this actually affects.

**Comment by radvansky-tomas** [comment]
@hpoul Absolutely don't understand why you've closed this issue... 

It's not resolved, will send PR soon, as OSX implementation is wrong...therefore it cant work as supposed to anyway

**Comment by radvansky-tomas** [comment]
@croquies And I can confirm that my Samsung s10 requires authentication EVERY time, no matter of 'authenticationValidityDurationSeconds'

**Comment by radvansky-tomas** [comment]
I read about android Keystore a lot (terrible docs btw)...but I understand it correctly, you can create biometric protected KEY and then use this key to encrypt file...and this key can have time-bound key, BUT you have to make decision wether to authenticate again YOURSELF.

https://android-developers.googleblog.com/2020/02/data-encryption-on-android-with-jetpack.html

Ie key is valid whilst inside `authenticationValidityDurationSeconds` but you have to measure it (keep timestamp) within plugin and ONLY re-authenticate if expired

**Comment by radvansky-tomas** [comment]
Still closed ?! Anyhow, for anyone interested, changes about + null-safety branch is in PR
https://github.com/authpass/biometric_storage/pull/20

**Comment by croquies** [comment]
> Still closed ?! Anyhow, for anyone interested, changes above + null-safety branch is in PR
> https://github.com/authpass/biometric_storage/pull/20

Thanks a lot for your PR!

**Comment by hpoul** [comment]
I've now implemented this slightly differently (catch exception, instead of manually keeping track of time). Should work now in `3.0.0-dev.1`.

**Comment by abdallah-odeh** [comment]
is there a way to force requesting authentication again when app-session is expired?
I set `authenticationValidityDurationSeconds: 60 * 10,` which is 10 minutes,
but during that 10 minutes if the user killed the app and reopened it, no biometric authentication is requested again!

or is there a way to write to "biometric protected" storage without biometric authentication?
