### ISSUE TITLE
Mention required proguard configuration in README

### ISSUE THREAD

**Issue by benjaminSchilling33** [authpass/biometric_storage#21]
Hi all,

I just tried to integrate this great package in freshly created flutter app with no other content.

I faced quite some problems getting it to build due to some ` java.lang.NoSuchMethodError: kotlin.jvm.internal.FunctionReferenceImpl.<init>` exceptions during the build.

Gladly I remembered a similar problem I had that required to enable Proguard.

I saw that you have enabled Proguard as well in this commit:
https://github.com/authpass/biometric_storage/commit/b37f0d7390b93ac21935862625348eebef5c4cdd

Maybe this information should be added to the README.

Looking forward to your comments.

Benjamin

**Comment by benjaminSchilling33** [comment]
See https://github.com/authpass/biometric_storage/pull/22

**Comment by Flajt** [comment]
Hello,
I have the same issue, I tried to implement what you wrote [here](https://github.com/authpass/biometric_storage/blob/1e6b0e40bec8c870dd9d0d7454d64db37619fc94/README.md) , but it seems to not work for me. And if I place:
`defaultConfig {
<...>
consumerProguardFiles 'proguard.pro'
<...>
}
` under android/build.grandle instead of android/app/build.grandle, I get another error, that the method default config is not found in this build.grandle.
Might the issue be that I use version: 1.1.0+1 instead of the newest one (I don't want to migrate to null safety just yet)?

**Comment by benjaminSchilling33** [comment]
@Flajt 

the `<..>` markers in the defaultConfig are placeholders for the stuff that is already in the defaultConfig.

So basically you only have to add `consumerProguardFiles 'proguard.pro'` to the end of the already exisiting defaultConfig

E.g. my complete build.gradle looks like this (for a fresh and not edited flutter app):

```

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 30
    ndkVersion "21.0.6113669"

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "application.id"
        minSdkVersion 24
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        consumerProguardFiles 'proguard.pro'
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}

```

**Comment by Flajt** [comment]
Aha thanks for the example, apparently it still crashes. Do I need to replace the `<fields>;` in the proguard.pro file with something (never used proguard before, so sorry for that) else aswell?

**Comment by benjaminSchilling33** [comment]
No, thats exactly what copied from the mentioned commit of the biometric_storage package

**Comment by hpoul** [comment]
I have just tried with a brand new project. I also got a compile error like `java.lang.NoSuchMethodError: kotlin.jvm.internal.FunctionReferenceImpl.<init>` but what fixed it for me, was simply updating the kotlin version from android/build.gradle:

```
diff --git a/android/build.gradle b/android/build.gradle
index c505a86..5af81e5 100644
--- a/android/build.gradle
+++ b/android/build.gradle
@@ -1,12 +1,12 @@
 buildscript {
-    ext.kotlin_version = '1.3.50'
+    ext.kotlin_version = '1.4.31'
```

imho, if you get any errors during debug builds, it has nothing to do with proguard/minifying.

**Comment by Flajt** [comment]
For me @hpoul idea did the trick (after I figured out how to the MainActivity.kt, for anybody interested: [here](https://stackoverflow.com/questions/60635356/error-platformexceptionno-fragment-activity-local-auth-plugin-requires-activi#62869991) is the link, I used to change it).
Now I'm only getting an: `Unhandled Exception: AuthException{code: AuthExceptionCode.unknown, message: Unexpected authentication error. the master key android-keystore://pw_master_key exists but is unusable}` error, but I guess that is a different issue.

**Comment by benjaminSchilling33** [comment]
I will check on my side again later the day. Most propably I identified ProGuard wrongly because I also changed the Kotlin Version.

I will update the PR accordingly.

**Comment by hpoul** [comment]
@flajt how are you testing? I've got a similar error in the android
emulator api 29, but it worked with 30.. imo there is some problem with the
emulators.. 🙄

**Comment by Flajt** [comment]
@hpoul Currently I'm testing on my personal device, with android 11, so might not be an emulator problem, but I'm not sure.

**Comment by benjaminSchilling33** [comment]
@hpoul
I updated https://github.com/authpass/biometric_storage/pull/22 accordingly

**Comment by hpoul** [comment]
I don't think there is any more to do regarding proguard. and the other error message (unusable master key) is nothing the plugin can fix imho. here are a few resources:

* https://issuetracker.google.com/issues/176215143
* https://www.reddit.com/r/android_devs/comments/kjgl3b/help_getting_a_weird_crash_when_using/ggwpy75/
* https://issuetracker.google.com/issues/158234058

if anyone has any idea how to work around this, feel free to open a new issue.
