### ISSUE TITLE
Android Lock Code with no fingerprint

### ISSUE THREAD

**Issue by syky27** [authpass/biometric_storage#24]
Hi, first of all thanks for your effort, I am using this package in my production app.

I have a question, would it be possible to authenticate user on Android when there is no fingerprint but the pass code/ pattern is set?

I am currently getting `CanAuthenticateResponse.errorNoBiometricEnrolled` 

Thank you.

**Comment by hpoul** [comment]
I think this should be fixed with https://github.com/authpass/biometric_storage/pull/28 by setting `allowBiometricOnly` to `false`. Maybe you can give `3.0.0-rc.5` a try.

**Comment by syky27** [comment]
Thanks! I'll check it out.
