### ISSUE TITLE
Permission error in linux

### ISSUE THREAD

**Issue by CodeDoctorDE** [authpass/biometric_storage#26]
When I use `flutter run -d linux -v`, this error appears:
```
[        ] CMake Error at cmake_install.cmake:66 (file):
[   +1 ms]   file INSTALL cannot copy file
[        ]   "/home/codedoctor/Dokumente/Flow/app/build/linux/x64/debug/intermediates_do_not_run/app"
[        ]   to "/usr/local/app": Permission denied.

```

I use fedora on my machine

**Comment by hpoul** [comment]
Can you give a few more details. I can't imagine how that error message is related to the plugin?

**Comment by CodeDoctorDE** [comment]
This are the only error that I get. If I remove the plugin, everything works fine.

**Comment by hpoul** [comment]
I've did a quick google for that error message and just found two problems reported, and both suggest running `flutter clean` - did you try that?

https://github.com/flutter/flutter/issues/59890
https://github.com/flutter/flutter/issues/73881#issuecomment-760216098

**Comment by CodeDoctorDE** [comment]
Oh thanks. After reboot it works and flutter clean it works.
