### ISSUE TITLE
Linux unauthenticated storage

### ISSUE THREAD

**Issue by CodeDoctorDE** [authpass/biometric_storage#27]
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(213)] Unhandled Exception: PlatformException(Bad Arguments, Linux plugin only supports non-authenticated secure storage, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
<asynchronous suspension>
#2      MethodChannelBiometricStorage.getStorage (package:biometric_storage/src/biometric_storage.dart:271:22)
<asynchronous suspension>
#3      main (package:flow_app/main.dart:21:26)
<asynchronous suspension>
```

I get this error if I use `await BiometricStorage().getStorage('key')`. In the readme, there is `No biometric authentication support`. How can I get the storage without biometric authentication?

**Comment by hpoul** [comment]
You might want to try the documentation https://pub.dev/documentation/biometric_storage/latest/biometric_storage/StorageFileInitOptions/authenticationRequired.html or example 

https://github.com/authpass/biometric_storage/blob/f829ed3d87f9df662e23e79b1b6403f919979585/example/lib/main.dart#L137-L141
