### ISSUE TITLE
Latest 3.0.0 version fails on android

### ISSUE THREAD

**Issue by killalad** [authpass/biometric_storage#32]
Latest version is throwing `BiometricStoragePlugin.kt: (265, 21): Unresolved reference: androidBiometricOnly`, which is probably  just caused by this commit `48a0182f3bfea2a7e9c96bbdb1d027371c3449f1`

**Comment by hpoul** [comment]
oops, thanks for the report. Seems like my last-minute find/replace was not successful 🤦‍♂️
just fixed it, can you please try `3.0.0-rc.2`
