### ISSUE TITLE
Minimum IOS version?

### ISSUE THREAD

**Issue by itaishalom** [authpass/biometric_storage#36]
Hi, on the main page it says that the plugin requires IOS 9 but on the link it says 11.3

https://developer.apple.com/documentation/localauthentication/logging_a_user_into_your_app_with_face_id_or_touch_id

So what is the right answer?

**Comment by hpoul** [comment]
I honestly have no idea why I've but that link there.. It should be iOS 9.
Did you experience any problems with iOS 9?

**Comment by itaishalom** [comment]
I didn't test it yet but I as I was reading about i reached that link and now I wandering why are the differences.
I thought you might have something to say.

**Comment by hpoul** [comment]
The link is about face id + touch id.. which is only available since ios 11 iirc, prior versions only have touch id
