### ISSUE TITLE
Question - android prompt

### ISSUE THREAD

**Issue by itaishalom** [authpass/biometric_storage#37]
Hi, is it possible to move the fingerprint prompt to the center of the screen like in the image attached?
Can we style the prompt?
![Screenshot_20210824-223626](https://user-images.githubusercontent.com/9066121/130679168-213f0b6b-93ed-4d29-856b-44edb4921fdc.png)

**Comment by hpoul** [comment]
the biometric prompt is provided by the system. Which incidentially, looks exactly like that 🤦‍♂️

![Screenshot_20210824-215507](https://user-images.githubusercontent.com/313066/130681328-21b6e99a-f8f6-4791-9c85-72f922c5efd9.png)

**Comment by Androrier** [comment]
In my phone it looks like this:
![WhatsApp Image 2021-08-25 at 12 47 23](https://user-images.githubusercontent.com/81566467/130768844-cfa63de3-278a-4e98-ba5c-0d704e586c2d.jpeg)

**Comment by hpoul** [comment]
It is provided by the system. Ie it depends on the system implementation.

**Comment by Androrier** [comment]
Hi, this is not entirely true, on the same phone i got 2 different prompts

**Comment by Androrier** [comment]
For example: (The one with the prompt down is yours..)
![20210825_133557](https://user-images.githubusercontent.com/81566467/130775931-d960aabd-55a7-4bfc-87c6-64a488938807.jpg)
![20210825_133613](https://user-images.githubusercontent.com/81566467/130775958-8920cae8-4f1c-46e0-838c-e4838a0fa2e5.jpg)

**Comment by hpoul** [comment]
https://developer.android.com/about/versions/pie/android-9.0#biometric-auth

> In Android 9, the system provides biometric authentication dialogs on behalf of your app. This functionality creates a standardized look, feel, and placement for the dialog, giving users more confidence that they're authenticating against a trusted biometric credential checker.

No it is not possible. If you want to use a deprecated api feel free to use another plugin.
