### ISSUE TITLE
Error on Android build

### ISSUE THREAD

**Issue by marcotrumpet** [authpass/biometric_storage#38]
Trying to build on Android and getting 

```
e: /Users/marcogaletta/.pub-cache/hosted/pub.dartlang.org/biometric_storage-3.0.0/android/src/main/kotlin/design/codeux/biometric_storage/BiometricStoragePlugin.kt: (275, 89): Unresolved reference: R
e: /Users/marcogaletta/.pub-cache/hosted/pub.dartlang.org/biometric_storage-3.0.0/android/src/main/kotlin/design/codeux/biometric_storage/BiometricStoragePlugin.kt: (280, 51): Unresolved reference: R

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':biometric_storage:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 59s
Exception: Gradle task assembleDevelopmentDebug failed with exit code 1
```

used `ext.kotlin_version = '1.4.31'` in build.gradle and added `biometric_storage: ^3.0.0` to pubspec.
It builds on ios simulator but never prompt me the faceID popup.

Do you have any guess?

**Comment by hpoul** [comment]
Try to use `compileSdkVersion 30` in your `app/build.gradle`

**Comment by marcotrumpet** [comment]
HI @hpoul thanks for the quick response. I already have `compileSdkVersion` set to `30`. Do you any other ideas? Seems doesn't recognize the android version when doing `val biometricOnly options.androidBiometricOnly || Build.VERSION.SDK_INT < Build.VERSION_CODES.R;`.

**Comment by hfierro** [comment]
Same error here. We also have compileSdkVersion set to 30.

**Comment by hpoul** [comment]
btw, have you tried `3.0.1-dev.1`?

**Comment by rockerhieu** [comment]
`3.0.1-dev.1` works for me

**Comment by hpoul** [comment]
ok, i've pushed `3.0.1` as stable. if there are still problems let me know.

**Comment by marcotrumpet** [comment]
Hey didn’t try it yet but great news! I want to ask (without opening other issue) if you now why on ios simulator (don’t know yet on real device) the fadeid system prompt doesn’t  shows up.

btw thank you for your job!
