### ISSUE TITLE
Error occured during writing on local storage

### ISSUE THREAD

**Issue by Muzammil-786** [authpass/biometric_storage#46]
PlatformException: PlatformException(AuthError:Failed, Plugin not attached to any activity., null, null)

**Comment by jackcasey** [comment]
Make sure to follow in instructions regarding changing `FlutterActivity` to `FlutterFragmentActivity`. If you have done that then I don't know.

**Comment by hpoul** [comment]
i guess @jackcasey  is right, if you still experience problems with `FlutterFragmentActivity` please leave another comment. otherwise i'll close the issue for now. thanks
