### ISSUE TITLE
fatal error: 'biometric_storage/biometric_storage-Swift.h' file not found

### ISSUE THREAD

**Issue by RafaRuiz** [authpass/biometric_storage#48]
(Android is working ok)
I'm following the whole documentation, and for iOS I'm getting:

```
/Users/gitlab/development/flutter/.pub-cache/hosted/pub.dartlang.org/biometric_storage-3.0.1/ios/Classes/BiometricStoragePlugin.m:2:9: fatal error: 'biometric_storage/biometric_storage-Swift.h' file not found
```

Flutter version:
```
Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (9 weeks ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4
```

Flutter doctor:
```
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.2 20D64 darwin-x64, locale en-GB)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
[✓] VS Code (version 1.61.0)
[✓] Connected device (2 available)
```

**Comment by RafaRuiz** [comment]
No matter how many times you run pod install, maybe at the 5th one will be the right one.
Lol.
Sorry.

**Comment by joshuaherr** [comment]
@RafaRuiz What was the solution to this problem? I am receiving the same error on MacOS but my Android build is working fine.

**Comment by hpoul** [comment]
@joshuaherr  this has nothing to do with `pod install`.. the `-Swift.h` bridge file should be generated by xcode during building. https://developer.apple.com/documentation/swift/importing-swift-into-objective-c

**Comment by joshuaherr** [comment]
Thanks for the response @hpoul I verified that the header files were properly generated. For some reason on the biometric_storage plugin the header files are not getting properly linked. Are there steps I need to to take to fix the linking issue in XCode then? (Sounds like this is a uniquely xcode problem).
