### ISSUE TITLE
Unexpected authentication error, only happening in Android release mode!

### ISSUE THREAD

**Issue by EhabSalah** [authpass/biometric_storage#56]
`biometric_storage: 4.0.0-dev.1`

```AuthException: AuthException{code: AuthExceptionCode.unknown, message: Unexpected authentication error. null}```

<img width="516" alt="image" src="https://user-images.githubusercontent.com/24505720/156338110-c16d515e-02ba-475c-91d1-ab3bc0764c05.png">

<img width="927" alt="image" src="https://user-images.githubusercontent.com/24505720/156338296-a224fea4-bdf6-4810-99a3-119ef6ad4950.png">

**Comment by EhabSalah** [comment]
I have migrated from this package!

**Comment by itaishalom** [comment]
@EhabSalah To which?
