### ISSUE TITLE
Does not work in iOS

### ISSUE THREAD

**Issue by WisdomStoneWorshiper** [authpass/biometric_storage#57]
Tried the following code, it write and read data, but it didn't ask use to do the touch ID
void _biometricHandler(BuildContext context) async {

    final response = await BiometricStorage().canAuthenticate();
    if (response == CanAuthenticateResponse.unsupported) {
      print("rip");
      errDialog(context, "This device do not support biometric");
      return;
    } else {
      print("should support");
      print(response.toString());
    }
    _pkStorage = await BiometricStorage().getStorage(
      'pk',
      options: StorageFileInitOptions(
        authenticationValidityDurationSeconds: 30,
        authenticationRequired: true,
      ),
      promptInfo: const PromptInfo(
        iosPromptInfo: IosPromptInfo(
          saveTitle: 'Custom save title',
          accessTitle: 'Custom access title.',
        ),
      ),
    );
    await _pkStorage!.write("test1");
    _getPk(_pkStorage!);
  }

  void _getPk(BiometricStorageFile bs) async {
    // print("hi");

    String? test = await bs.read();
    print(test);
  }

**Comment by hpoul** [comment]
[have you tried in the simulator or a real device?](https://github.com/authpass/biometric_storage/issues/61#issuecomment-1107362106)
