### ISSUE TITLE
Clarify what "not massive amounts of data" means

### ISSUE THREAD

**Issue by Goddard** [authpass/biometric_storage#60]
This is kind of vague on what you mean by this.  Does this mean you shouldn't treat it as a database?  Does this mean you shouldn't store large files?  What does this mean exactly and why. 

Thanks

**Comment by hpoul** [comment]
You might want to get yourself familiar with the underlying technologies mentioned on the README as well. Keychain, KeyStore, etc. each has it's own limits, most of the time not really well documented.
In addition the plugin uses flutter message channels, which don't lend themselves to gigabytes of data anyway.. so just use it for what it is meant.. ie. passwords and security keys. If you need to store large data, store a secret key in the secured storage and use it to encrypt data you write into a local file directly using dart:io File API.

**Comment by afzl-wtu** [comment]
> 

Is there any alternate package which can store large amount of data and provide on the fly encrytion decryption? Like playing encrypted movie in a media player without decrypting on local storage.
