### ISSUE TITLE
iOS Simulator FaceID never popups

### ISSUE THREAD

**Issue by oliverbytes** [authpass/biometric_storage#61]
FaceID is enrolled in Simulator settings

Code
```
final storage = await BiometricStorage().getStorage('test');

try {
  await storage.write('value');
} catch (e) {
  return console.error('biometric error: $e');
}
```

Error
` PlatformException(SecurityError, Error while writing data: -25293: The user name or passphrase you entered is not correct., null, null)`

**Comment by hpoul** [comment]
Iirc the simulator will not show any ui, it will just stimulate matching it non matching api responses.
Did you test on a device? https://stackoverflow.com/a/47160418/109219

**Comment by oliverbytes** [comment]
> Iirc the simulator will not show any ui, it will just stimulate matching it non matching api responses. Did you test on a device? https://stackoverflow.com/a/47160418/109219

I believe it's a real issue. If you try and run it on an emulator and test getStorage() you won't see any FaceID popup. And throws an error

**Comment by oliverbytes** [comment]
> @oliverbytes Did you try with the real device? I haven't yet checked with the real device

Works well on a real device

**Comment by sgorbyo** [comment]
> > @oliverbytes Did you try with the real device? I haven't yet checked with the real device
> 
> Works well on a real device

Well, it is still an issue. To test on iOS you should have at least some device with fingerprint and another one with faceId...

**Comment by hpoul** [comment]
Since it's a problem with the simulator, not with the package, i'll close this issue.
If someone knows a workaround or another plugin which solves this somehow, let me know.

**Comment by mekhri-codex** [comment]
@oliverbytes did you do something special for it works on real device? for me it doesn't

**Comment by RizanPSTU** [comment]
Does anyone found any solution?
