### ISSUE TITLE
MacOS Password popup

### ISSUE THREAD

**Issue by edeuss** [authpass/biometric_storage#65]
Is this required to have a password entered to save stuff to the keychain? flutter_secure_storage Doesn't cause this popup. 

<img width="450" alt="Screen Shot 2022-06-14 at 8 29 02 PM" src="https://user-images.githubusercontent.com/13773566/173962367-1b5f285b-47e9-4130-8dee-0949461a5695.png">

**Comment by hpoul** [comment]
I don't get it.. thats the whole point of biometric storage.. to require user authentication.. either through fingerprint, face id.. or password.. if you don't want this, have you tried setting `authenticationRequired` to false? https://pub.dev/documentation/biometric_storage/latest/biometric_storage/StorageFileInitOptions-class.html

**Comment by edeuss** [comment]
@hpoul I have it set to false, and the prompt still pops up.

**Comment by hpoul** [comment]
@edeuss is it possible that you changed `authenticationRequired` only after having written it once? it has to be set when writing the first time.. after that you would have to delete it and recreate it.. You can also change the name and try again

fwiw, I've just tried the example app and when writing/reading from the unauthenticated storage no password prompt is shown.

**Comment by hpoul** [comment]
then just try to enable automatic signing 🤷‍♂️
