### ISSUE TITLE
Request face id authentication every time open the storage

### ISSUE THREAD

**Issue by emanuelemarchesotti** [authpass/biometric_storage#72]
Hello,
I have problem with biometric_storage plugin. On ios 15.5  the first time that open the biometric storage i use the face id, but the second time the biometric storage is already open and i can't use the face id again. I tried to set "authenticationValidityDurationSeconds"  parameter to: -1 (default value), 0 and 1 but the result doesn't change.

Thanks in advance

**Comment by hpoul** [comment]
Hard to guess what you mean, but sounds like 

* #68

**Comment by emanuelemarchesotti** [comment]
Yes, it's the same problem. Sorry I didn't see that there was another issue open. I will wait for the next update. Thank you

**Comment by abdallah-odeh** [comment]
Closed as completed? is the issue solved?
