### ISSUE TITLE
[Android] EncryptedSharedPreferences

### ISSUE THREAD

**Issue by hm122** [authpass/biometric_storage#78]
Hi,

is there any reason why on Android `KeyStore` was used instead of `EncryptedSharedPreferences`?

**Comment by hpoul** [comment]
EncryptedSharedPreferences is only a [buggy](https://issuetracker.google.com/issues/176215143?pli=1) abstraction for the underlying KeyStore .. 

I also don't see his this qualifies as an issue

**Comment by hm122** [comment]
Wasn't aware of the issues actually, used it a lot without issues and thought it would reduce complexity in the plugin.
But you are right, wasn't probably the right way to open an issue. Anyways, thanks for the fast reply and the plugin development.
