### ISSUE TITLE
Validation for LockedOut and PermanentlyLockedOut

### ISSUE THREAD

**Issue by EdinsonNM** [authpass/biometric_storage#8]
Hi, 
Is it possible to add inside BiometricStorage().canAuthenticate() the validations for
 LockedOut and PermanentlyLockedOut?

**Comment by hpoul** [comment]
I don't think so .. i guess you mean [BIOMETRIC_ERROR_LOCKOUT](https://developer.android.com/reference/android/hardware/biometrics/BiometricPrompt#BIOMETRIC_ERROR_LOCKOUT)?
as far aas i can tell these error codes are only returned when showing a prompt, i [have not found an API to check for lockout](https://developer.android.com/reference/android/hardware/biometrics/BiometricManager#canAuthenticate())?

**Comment by EdinsonNM** [comment]
I noticed that the read method is returning the error message :)
