### ISSUE TITLE
Request Error Type for "At least one biometric must be enrolled to create keys requiring user authentication for every use"

### ISSUE THREAD

**Issue by pearlmaknun** [authpass/biometric_storage#83]
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(Unexpected Error, java.lang.IllegalStateException: At least one biometric must be enrolled to create keys requiring user authentication for every use, java.security.InvalidAlgorithmParameterException: java.lang.IllegalStateException: At least one biometric must be enrolled to create keys requiring user authentication for every use
E/flutter (26262): java.security.InvalidAlgorithmParameterException: java.lang.IllegalStateException: At least one biometric must be enrolled to create keys requiring user authentication for every use

**Comment by hpoul** [comment]
Nice error message 🤷‍♂️
If you expect anyone to look at your problem you might want to be a bit more elaborate... What did you try, how did you try to solve the issue, what outcome did you expect, how to reproduce the problem, etc, etc. Good luck next time.
