### ISSUE TITLE
Example file doesn't work on pub.dev mentioned version.

### ISSUE THREAD

**Issue by brunotacca** [authpass/biometric_storage#9]
Actual example uses BiometricStorage().linuxCheckAppArmorError() which was added at 4.1.0 and later, while pub.dev reffers to 4.0.0

Thanks.

**Comment by hpoul** [comment]
You are right, i haven't published a new version for a while. I've just pushed 1.0.0 to pub.. maybe you can give this one a try and let me know if it works for you.
thanks

**Comment by brunotacca** [comment]
Works fine! Good work.

Thanks.
