### ISSUE TITLE
Is this package abandoned?

### ISSUE THREAD

**Issue by annawidera** [authpass/biometric_storage#97]
Hey! I'm working on a flutter app where biometric-gated encrypted storage is crucial. This package sounds like a perfect fit by covering `Keychain` on iOS and `KeyStore` on Android, plus setting authentication requirements on stored items. 

I'd appreciate very much being able to use it in the project I'm concerned about the current status of the package, though. 

Significant security-related changes for iOS are currently not released. They are available only on the `main` branch (I mean providing fresh `LAContext` into every read on iOS and setting flags appropriate for invalidating the content automatically upon biometry configuration changes). 

Developments towards optimising the iOS and macOS behaviour seem stuck, going through #68, #73 and #77 with additional discussion about the changes in #73 tracked in #74. 

Please, let us know the current plan for the package and its further development. Thanks! 🙌🏻

**Comment by bjernie** [comment]
I emailed the publisher of the package and he says that it is not abandoned as they are still using it in the authpass app

**Comment by hpoul** [comment]
fwiw, i've now merged #77 feel free to test `5.1.0-rc.1` and let me know if it works..
